.PHONY: install dev build test test-watch test-e2e lint

install:
	npm install

dev:
	npm run dev

build:
	npm run build

test:
	npm run test

test-watch:
	npm run test:watch

test-e2e:
	npm run test:e2e

lint:
	npm run lint
