services:
  postgres:
    image: postgres:17-alpine
    env_file:
      - ./.env.compose
    environment:
      POSTGRES_DB:       todoist
      POSTGRES_USER:     todoist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todoist"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
