// @title           Todoist Clone API
// @version         1.0
// @description     Multi-tenant REST API for Todoist Clone — tasks, projects, labels, comments.
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
// @description     Type "Bearer" followed by a space and your JWT access token.
package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/todoist/backend/docs" // generated by swag init

	"github.com/todoist/backend/internal/config"
	"github.com/todoist/backend/internal/db"
	"github.com/todoist/backend/internal/handler"
	"github.com/todoist/backend/internal/repository"
	"github.com/todoist/backend/internal/service"
)

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	cfg, err := config.Load()
	if err != nil {
		logger.Error("load config", slog.String("err", err.Error()))
		os.Exit(1)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	pool, err := db.New(ctx, cfg.DatabaseURL)
	if err != nil {
		logger.Error("connect to database", slog.String("err", err.Error()))
		os.Exit(1)
	}
	defer pool.Close()

	// Wire repositories.
	userRepo := repository.NewUserRepo(pool)
	tokenRepo := repository.NewTokenRepo(pool)
	projectRepo := repository.NewProjectRepo(pool)
	taskRepo := repository.NewTaskRepo(pool)
	labelRepo := repository.NewLabelRepo(pool)
	commentRepo := repository.NewCommentRepo(pool)

	txManager := db.NewTxManager(pool)

	// Wire services.
	authSvc := service.NewAuthService(
		userRepo, tokenRepo, txManager,
		cfg.JWTSecret, cfg.AccessTokenExpiry, cfg.RefreshTokenExpiry,
		cfg.BCryptCost,
	)
	projectSvc := service.NewProjectService(projectRepo, taskRepo)
	taskSvc := service.NewTaskService(taskRepo, projectRepo, labelRepo, txManager)
	labelSvc := service.NewLabelService(labelRepo)
	commentSvc := service.NewCommentService(commentRepo, taskRepo)

	// Wire handlers.
	deps := handler.Deps{
		Auth:        handler.NewAuthHandler(authSvc),
		Users:       handler.NewUserHandler(userRepo),
		Projects:    handler.NewProjectHandler(projectSvc),
		Tasks:       handler.NewTaskHandler(taskSvc),
		Labels:      handler.NewLabelHandler(labelSvc),
		Comments:    handler.NewCommentHandler(commentSvc),
		AuthService: authSvc,
	}

	srv := &http.Server{
		Addr:         fmt.Sprintf(":%s", cfg.Port),
		Handler:      handler.NewRouter(deps, logger),
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	go func() {
		logger.Info("server starting", slog.String("addr", srv.Addr))
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Error("server error", slog.String("err", err.Error()))
			os.Exit(1)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	shutCtx, shutCancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer shutCancel()
	if err := srv.Shutdown(shutCtx); err != nil {
		logger.Error("graceful shutdown failed", slog.String("err", err.Error()))
	}
	logger.Info("server stopped")
}
