// Package docs is generated by swag. Run "make swagger" to regenerate.
// This placeholder exists so the project compiles before swag has been run.
package docs

import "github.com/swaggo/swag"

func init() {
	swag.Register(swag.Name, &swag.Spec{
		InfoInstanceName: swag.Name,
		SwaggerTemplate:  `{"swagger":"2.0","info":{"title":"Todoist Clone API","version":"1.0"},"paths":{}}`,
	})
}
